export const ingredients: string[] = [
    "Rice",
    "Onion",
    "Zucchini",
    "Green Onion",
    "Potato",
    "Cucumber",
    "Chili Pepper",
    "Garlic",
    "Ginger",
    "Soy Sauce",
    "Rice Vinegar",
    "Kimchi",
    "Spam",
    "Pork",
    "Beef",
    "Chicken",
    "Sesame Oil",
    "Broccoli",
    "Carrot",
    "Noodles",
    "Tofu",
    "Eggs",
    "Gochujang",
];

export const foodStyles: string[] = [
    "With rice",
    "Noodles",
    "Hot soup",
    "Cold soup",
    "Stir Fry",
];

export const colors: string[] = [
    "red",
    "orange",
    "amber",
    "yellow",
    "lime",
    "green",
    "emerald",
    "violet",
    "purple",
    "fuchsia",
    "pink",
    "rose",
];
